version: '3.8'

services:
  app:
    image: python:3.9-slim
    container_name: Global-Price-Comparison-Tool
    working_dir: /comparing-apps  # <--- match volumes path
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/comparing-apps/app.py
      - ./requirements.txt:/comparing-apps/requirements.txt
      - ./templates:/comparing-apps/templates
    environment:
      - SECRET_KEY=super-secret-key-ulemt-2025
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python app.py"
    restart: unless-stopped

volumes:
  logs:
